//Check for validations on booking tickets and betting pages

describe('Validations', ()=>{
    //VALIDATION ON BOOKING TICKETS
    it('Validation on booking tickets WITHOUT PASSING any input values', ()=>{
        cy.visit('http://localhost:4200/user/login')
        cy.url().should('contain', 'login')
        cy.get('input[placeholder="Email"]').type('admin@admin.com')
        cy.get('input[placeholder="Password"]').type('123456')
        cy.get('.btn').contains('login').click()
        cy.get('li a').contains('Booking').click()
        cy.url().should('contain', '/fixtures/booking')
        cy.get('.btn').contains('Book the ticket').click()
    })
    it('Validation on booking tickets by CLICKING ON INPUT FIELDS BUT WITHOUT PASSING ANY VALUES', ()=>{
        cy.visit('http://localhost:4200/user/login')
        cy.url().should('contain', 'login')
        cy.get('input[placeholder="Email"]').type('admin@admin.com')
        cy.get('input[placeholder="Password"]').type('123456')
        cy.get('.btn').contains('login').click()
        cy.get('li a').contains('Booking').click()
        cy.get('#email').click().invoke('val', '')
        cy.get('#cardInfo').click().invoke('val', '')
        cy.get('.btn').contains('Book the ticket').click()
    })
    it('validation on booking ticket by by passing an INVALID EMAIL FORMAT', ()=>{
        cy.visit('http://localhost:4200/user/login')
        cy.url().should('contain', 'login')
        cy.get('input[placeholder="Email"]').type('admin@admin.com')
        cy.get('input[placeholder="Password"]').type('123456')
        cy.get('.btn').contains('login').click()
        cy.get('li a').contains('Booking').click()
        cy.get('#email').type('test.com.com')
        cy.get('#cardInfo').type('12334')
        cy.get('.btn').contains('Book the ticket').click()
    })

     //VALIDATION ON BETTING PAGE
     it('Validation on placing the bet WITHOUT PASSING any input values', ()=>{
        cy.visit('http://localhost:4200/user/login')
        cy.url().should('contain', 'login')
        cy.get('input[placeholder="Email"]').type('admin@admin.com')
        cy.get('input[placeholder="Password"]').type('123456')
        cy.get('.btn').contains('login').click()
        cy.get('td .btn').contains('Bet').first().click()
        cy.url().should('include', 'fixtures/bet')
        cy.get('.btn').contains('Place the bet').click()
    })
    it('Validation on placing the bet by CLICKING ON INPUT FIELDS BUT WITHOUT PASSING ANY VALUES', ()=>{
        cy.visit('http://localhost:4200/user/login')
        cy.url().should('contain', 'login')
        cy.get('input[placeholder="Email"]').type('admin@admin.com')
        cy.get('input[placeholder="Password"]').type('123456')
        cy.get('.btn').contains('login').click()
        cy.get('td .btn').contains('Bet').first().click()
        cy.get('#cardInfo').click().invoke('val', '')
        cy.get('#homeScore').click().invoke('val', '')
        cy.get('#awayScore').click().invoke('val', '')
        cy.get('#amount').click().invoke('val', '')
        cy.get('.btn').contains('Place the bet').click()
    })
})